apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-create-invoices
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: create-invoices-container
            image: martinfrick/cron-create-invoices
            imagePullPolicy: Always
            envFrom:
              - secretRef:
                  name: cron-config-secret