apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cap-invoice-cron-job
spec:
  schedule: "0 0 2 * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cap-invoice-cron-job
            image: curlimages/curl
            imagePullPolicy: IfNotPresent
            command:
            - sh
            - -c
            args:
            - curl $SERVICE_URL
            env:
            - name: SERVICE_URL
              value: "$(INVOICING_SERVICE_HOST).$(INVOICING_SERVICE_NAMESPACE)/$(INVOICING_SERVICE_PATH)/createStripeInvoices()"
          restartPolicy: OnFailure