apiVersion: v1
kind: Service
metadata:
  name: {{ include "cap-orders-service.fullname" . }}
  labels:
    {{- include "cap-orders-service.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "cap-orders-service.labels" . | nindent 4 }}