apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cap-orders-service.fullname" . }}
  labels:
    {{- include "cap-orders-service.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "cap-orders-service.labels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        releaseTime: {{ dateInZone "2006-01-02 15:04:05Z" (now) "UTC"| quote }}
      labels: # labels to select/identify the deployment
        {{- include "cap-orders-service.labels" . | nindent 8 }}
    spec: # pod spec
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          name: {{ .Chart.Name  }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          envFrom:
            - secretRef:
                name: {{ .Values.vcapsecret.name }}
            - configMapRef:
                name: {{ include "cap-orders-service.fullname" . }}
