apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "orders-db-deployer.fullname" . }}
  labels:
    {{- include "orders-db-deployer.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-weight": "1"
spec:
  template:
    metadata:
      labels:
        {{- include "orders-db-deployer.labels" . | nindent 8 }}
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: OnFailure
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Chart.Name }}
          envFrom:
          - secretRef:
              name: {{ .Values.secretRefName }}